### ISSUE TITLE
Feature Request: Show nuget dependencies

### ISSUE THREAD

**Issue by zplan** [clovett/DgmlPowerTools#1]
Hi and congratulations to your VS extension. 
I like it, especially the VS2022 version with the feature to create a project dependencies graph!

Feature Request:
When creating the project dependencies graph it would be nice to optionally include also the nuget package references of the projects with another color. A button in the toolbar could then allow the user to show/hide the nuget packages on the diagram.
Display the nuget version besides the name would be nice to see if different versions of the same nuget package are referenced.

**Comment by lovettchris** [comment]
Great idea, feel free to post a PR.  I don't have much time these days to add more features so not sure when I'll get to it.

**Comment by zplan** [comment]
Integrated with PR #2
