### ISSUE TITLE
C++ project type icons

### ISSUE THREAD

**Issue by wilhelmmedetz** [clovett/DgmlPowerTools#7]
Would it be possible to display different icons for C++ projects (maybe differentiating native/mnaged projects?)

**Comment by lovettchris** [comment]
I added some project type icons in version 2.0.11:

![image](https://github.com/clovett/DgmlPowerTools/assets/18707114/8286e8bc-f9dd-40c1-99f5-53e3bec29146)

**Comment by wilhelmmedetz** [comment]
Thanks :)
