### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by michaldengusiak** [clovett/DgmlPowerTools#8]
Hi,

I could find source to ask question so will use issue to find out how to run it. 
I manage to install DgmlPowerTools via extension in VS 2022.

In VC try to open File and .dgml but is not recognized.

in your https://github.com/clovett/DgmlPowerTools help
you mention 'you drop a random .dll onto a new Directed Graph Document' where I find 'Directed Graph Document' ?
This is new project in VS or new File?

**Comment by clovett** [comment]
Go to the Visual Studio Installer, Individual Components and make sure DGML editor is "checked":

![image](https://github.com/clovett/DgmlPowerTools/assets/3336415/7b8d7110-0ce5-4769-b5c7-0e45f8ebdd0d)

**Comment by robsiera** [comment]
> Go to the Visual Studio Installer, Individual Components and make sure DGML editor is "checked":

A vital piece of information that you might want to consider adding to your introduction text. :-)

Thank you for all your effort towards this project!

**Comment by clovett** [comment]
Good idea, done.
