### ISSUE TITLE
Is it possible to use DGML editor on vscode community edition?

### ISSUE THREAD

**Issue by learnwell** [clovett/DgmlPowerTools#9]
1. I have:
```
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.4.0
```
2. does not show up in extensions search on its own
3. i downloaded the `vsix` file from `https://marketplace.visualstudio.com/items?itemName=ChrisLovett.DgmlPowerTools2022` and then install it via the `vsix` file but it errors out saying that `extension/package.json not found inside zip`

Thank you for making this awesome tool based on what I see on your videos :)

**Comment by clovett** [comment]
Yes, you can enable the DGML Editor using the "Visual Studio Installer" click on "Individual Components" search for DGML, check the box, then apply  the changes and you will get DGML editor support.

**Comment by pulkitsinghal** [comment]
I use mac not windows, does that make a difference? No Wait figured it out!
Putting 10 second [video](https://youtu.be/tSvA1CsM7tM) for anyone else using a mac.
Please go ahead and close this issue as resolved 👍

**Comment by clovett** [comment]
Yeah, sorry none of it is available on Mac as far as I know.
